apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-container-templ-
spec:
  entrypoint: container-template
  templates:
    - name: container-template
      container:
        image: python:3.8-slim
        command: [echo]
        args: ["Hello, from within container running argo workflow"]
