apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-resource-tmpl-
spec:
  entrypoint: resource-template
  templates:
    - name: resource-template
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            name: wf-res-spawn
          spec:
            entrypoint: script-template
            templates:
              - name: script-template
                script:
                  image: python:3.8-slim
                  command: [python]
                  source: |
                    print("WF spawned by another res wf.")